header_pages: []
title: "Richard \"Max\" Melstrom, PhD"
description: Economist | Professor | Consultant, specializing in environmental and natural resource valuation, damage assessment, and cost-benefit analysis.
theme: minima
