header_pages: []
title: "Richard \"Max\" Melstrom, PhD"
description: Economist | Professor | Consultant, specializing in economic damage, environmental valuation, and cost-benefit analysis.
theme: minima
plugins:
  - jekyll-sitemap
